Example workbooks for the time series academy track
crate/cratedb-examples pull request #246
Opened 2024-01-25 14:08 UTC by ckurze

## Summary of the changes / Why this is an improvement

## Checklist

 - [ ] Link to issue this PR refers to (if applicable): 
 - [ ] [CLA](https://crate.io/community/contribute/cla/) is signed

2024-01-25 23:34 UTC, amotl requested changes
Thanks for submitting this. I did not do a thorough review yet, but I have two requests about layout/structure.

2024-01-25 23:34 UTC, amotl commented on topic/timeseries/timeseries-queries-and-visualization.ipynb
It looks like this file is already present within the tree. Can I ask you to remove it from this patch, and submit eventual updates seperately?

https://github.com/crate/cratedb-examples/blob/main/topic/timeseries/explore/timeseries-queries-and-visualization.ipynb

2024-01-25 23:34 UTC, amotl commented on topic/timeseries/academy/batch_import_sample_weather_data_dask.ipynb
Despite this notebook might be targeted to the academy track, please don't introduce a separate subfolder. We can't map out the whole ontology on all axes into the filesystem hierarchy. "Flat" style is always preferred to "nested" style. Thanks!

NB: Saying that, I am also +1 on stripping the `explore` folder from the path to the other notebook. It's just nonsense.

2024-01-29 21:17 UTC, ckurze commented on topic/timeseries/academy/batch_import_sample_weather_data_dask.ipynb
Agreed! Let's wait with the removal of "explore" after our event this week, we already have some printed materials referencing it.

2024-01-29 21:58 UTC, amotl commented on topic/timeseries/academy/batch_import_sample_weather_data_dask.ipynb
PRINTED!? ;]

2024-01-29 21:59 UTC, amotl commented on topic/timeseries/academy/batch_import_sample_weather_data_dask.ipynb
I am fine with waiting for dissolving the `explore` folder. But can the `acadamy` folder be omitted from the very beginning, in order not to make the same mistakes, if you agree?

2024-02-12 18:41 UTC, amotl commented
Hi. Because conflicts on this branch haven't been able to be resolved properly, the new notebook has been broken out into a different PR.

- GH-293

There is also a followup patch for that, adding a few copy-edits.

- GH-294

Thus, I am closing this PR. Feel free to re-open if you think anything has been forgotten.

2024-02-12 18:41 UTC, closed without merging